config/routes.rb
Rails.application.routes.draw do
  # get 'homerails/routes'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root to: "products#main"
  # User Routes
  get '/users/:id', to: 'users#show', as: 'user'
  patch "/users/:id", to: "users#update"

  get '/users/:id/edit', to: 'users#edit', as: "user_edit"


  # Product Routes
  get "/products", to: "products#index", as: "products"

  get "/products/new", to: "products#new", as: "new_product"

  get "/products/:id", to: "products#show", as: "product"

  post "/products", to: "products#create"

  get "/products/:id/edit", to: "products#edit", as: "edit_product"

  patch "/products/:id", to: "products#update"

  delete "/products/:id", to: "products#destroy"



  # Stripe Charges
  resources :charges, only: [:index, :new, :create]
    

end

app/models/user.rb
class User < ApplicationRecord

  has_many :charges
  has_many :products, through: :charges


  validates :first_name, presence: true, length: {maximum: 50}
  validates :last_name, presence: true, length: {maximum: 50}
  validates :email,
    presence: true,
    uniqueness: true,
    length: {maximum: 100},
    format: {
      with: /@/,
      message: "not a valid format"
    }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :current_user?
  before_action :set_user, except: [:show]


  def show
    if check_id?(params[:id])
      @user = User.find(params[:id])
    elsif current_user == nil
      redirect_to root_path
    else
      @user = current_user
    end

    # THIS SHOULD BE CHANGED
    @product = Product.last
    @products = Product.all
    if @product != nil
      @charges = @product.charges
    end
  end

  def edit
  end

  def update
    @user.update_attributes(user_params)
    redirect_to user_path(@user)
  end


  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name)
  end

  def set_user
    user_id = params[:id]
    @user = User.find_by_id(user_id)
  end

  def check_id?(params)
    User.exists?(params)
  end

  def current_user?
    if (current_user != User.find(params[:id]))
      flash[:danger] = "Not authorized to view page."
      if signed_in?
        redirect_to user_path(current_user)
      else
        redirect_to root_path
      end
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper



end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="form-group">
    <div class="form-group">
      <%= f.label :emaile %>
      <%= f.text_field :email, placeholder: "Email", class: "form-control", autofocus: true, :required => true %>
    </div>
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: "First Name", class: "form-control", autofocus: true, :required => true %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control", autofocus: true, :required => true %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-block" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit User</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= render "form", user: @user %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <br>
  <h3 class="text-center">Welcome to your Dashboard, <%= current_user.first_name %></h3>
  <br>
  <hr>
  <br>

  <div class="container">
    <%= button_to "Add Customer", new_charge_path, :method => "get", class: "btn btn-info" %>
    <% if @product != nil %>
      <%= button_to "See Current Product", product_path(@product), :method => "get", class: "btn btn-primary pull-right" %>
      <% end %>
    <br>
    <span class="pull-left"><%= link_to "Edit Profile", user_edit_path(@user.id) %></span>
    <br>
    <br>
    <div class="col-sm-6">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title text-center">Total Donations</h3>
            </div>
            <div class="panel-body text-center">
              <!-- conditional to prevent the site from breaking when there are no products -->
              <% if @product != nil %>
                <h4>$<%= @product.total_donated_amount %></h4>
              <% else %>
                <h4> n/a </h4>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title text-center">Minimum Price</h3>
            </div>
            <div class="panel-body text-center">
              <!-- conditional for if there are no products -->
              <% if @product != nil %>
                <h4>$<%= @product.min_price %></h4>
              <% else %>
                <h4> n/a </h4>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>



    <div class="col-sm-6">
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title text-center">
                <!-- conditional for if there are no products -->
                <% if @product != nil %>
                  Total Donors for <%= link_to "#{@product.name}", product_path(@product) %></h3>
                <% else %>
                  <h4> Total Donors for n/a </h4>
                <% end %>
            </div>
            <div class="panel-body text-center">
            <!-- conditional for if there are no products -->
              <% if @product != nil %>
                <h4><%= @product.charges.length %></h4>
              <% else %>
                <h4>n/a</h4>
              <% end %>

            </div>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title text-center">Inventory</h3>
            </div>
            <div class="panel-body text-center">
              <!-- conditional in case of no products -->
              <% if @product != nil %>
                <h4><%= @product.inventory_amount %></h4>
              <% else %>
                <h4> n/a </h4>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>
<br>

  <!-- LIST OF DONORS -->

  <div class="container">
    <hr><h3 class="text-center"> Recent Donations</h3><hr>
    <% if @product != nil %>
      <div class="row">
        <div class="col-lg-12">
          <div class="table-responsive table-center">
              <table class="table table-bordered table-hover table-striped">
                  <thead>

                    <tr>
                      <th><%=  "Date" %></th>
                      <th><%=  "Customer" %></th>
                      <th><%=  "Donation" %></th>
                      <th><%=  "Product Id" %></th>
                    </tr>

                  </thead>
                  <tbody>

                    <% @charges.each do |charge| %>
                      <tr>
                          <td><%= (charge.created_at).strftime("%b %d, %Y")  %> </td>
                          <td><%= charge.customer_name.titleize %> </td>
                          <td>$<%= charge.amount %> </td>
                          <% if charge.product_id == nil %>
                            <td> n/a </td>
                          <% else %>
                            <td><%= charge.product_id %> </td>
                          <% end %>

                      </tr>
                    <% end %>
                  </tbody>
              </table>
          </div>
          <!-- /.table-responsive -->
          </div>
      </div>
    <% else %>
      <h4>No product yet!</h4>
    <% end %>
  </div>
</div>