config/routes.rb
Rails.application.routes.draw do
  # get 'homerails/routes'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root to: "products#main"
  # User Routes
  get '/users/:id', to: 'users#show', as: 'user'
  patch "/users/:id", to: "users#update"

  get '/users/:id/edit', to: 'users#edit', as: "user_edit"


  # Product Routes
  get "/products", to: "products#index", as: "products"

  get "/products/new", to: "products#new", as: "new_product"

  get "/products/:id", to: "products#show", as: "product"

  post "/products", to: "products#create"

  get "/products/:id/edit", to: "products#edit", as: "edit_product"

  patch "/products/:id", to: "products#update"

  delete "/products/:id", to: "products#destroy"



  # Stripe Charges
  resources :charges, only: [:index, :new, :create]
    

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :charges
  has_many :users, through: :charges


  validates :name, presence: true, length: {maximum: 50}
  validates :description, presence: true, length: {maximum: 500}
  validates :min_price, :inventory_amount, presence: true, numericality: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :require_login, except: [:main]

  def main
    @product = Product.last
    @products = Product.all
    @users = User.all
    @charges = Charge.all
  end

  def index
    @products = Product.all
    @users = User.all
    @charges = Charge.all
  end

  def show
    product_id = params[:id]
    @product = Product.find_by_id(product_id)
  end

  def new
    if signed_in?
      @product = Product.new
    else
      flash[:notice] = "Log in to create a new product"
      redirect_to root_path
    end
  end

  def create
    product_params[:inventory_amount] = 0
    @product = Product.create(product_params)
    redirect_to @product
  end

  def edit
    product_id = params[:id]
    @product = Product.find_by_id(product_id)
  end

  def update
    product_id = params[:id]
    @product = Product.find_by_id(product_id)
    @product.update_attributes(product_params)
    redirect_to product_path(@product)
  end

## need to se archive or something
  def destroy
    product_id = params[:id]
    @product = Product.find(product_id)
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :min_price, :total_donated_amount, :inventory_amount, :avatar)
  end

  def require_login
    if !(signed_in?)
      flash[:danger] = "Please log in."
      redirect_to root_path
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
   <div class="form-group">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, placeholder: "Product Name", class: "form-control", autofocus: true, :required => true %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description, placeholder: "Must be under 500 characters", class: "form-control", autofocus: true, :required => true %>
    </div>
    <div class="form-group">
      <%= f.label :minimum_price %>
      <%= f.text_field :min_price, placeholder: "Minimum Acceptable price", class: "form-control", autofocus: true, :required => true %>
    </div>
    <div class="form-group">
      <%= f.label :image_url %>
      <%= f.text_field :avatar, placeholder: " www.example.com/image.jpg", class: "form-control", autofocus: true %>
    </div>
    <div class="form-group">
      <%= f.label :inventory_amount %>
      <%= f.text_field :inventory_amount, placeholder: "Has your inventory changed?", autofocus: true, class: "form-control", :required => true%>
    </div>

      <div class="row">
    <%= f.hidden_field :total_donated_amount, :value => 0 %>
  </div>
    <div class="actions">
      <%= f.submit "Save", class: "btn btn-block" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit Product</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= render "form", product: @product %>

    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <hr><h3 class="text-center"> All Products</h3><hr>
  <div class="row">
    <div class="col-lg-12">
      <div class="table-responsive table-center">
          <table class="table table-bordered table-hover table-striped">
              <thead>

                <tr>
                  <th><%= "Date Added" %></th>
                  <th><%= "Product Name" %></th>
                  <th><%= "Total Donated" %></th>
                  <th><%= "Product Id" %></th>
                </tr>

              </thead>
              <tbody>
                <% @products.each do |product| %>
                  <tr>
                      <td><%= (product.created_at).strftime("%b %d, %Y")  %> </td>
                      <td><%= link_to "#{product.name}", product_path(product) %>
                      </td>
                      <td>$<%= product.total_donated_amount %> </td>
                      <td><%= product.id %> </td>

                  </tr>
                <% end %>
              </tbody>
          </table>
      </div>
      <!-- /.table-responsive -->
      </div>
  </div>
</div>

app/views/products/main.html.erb
<br>
<br>
<br>

<div class="container">
    <div class="row product">
        <div class="col-md-5 col-md-offset-0">
            <div class=""></div>
            <% if (@product == nil) || (@product.avatar == "") || (@product.avatar == nil)  %>
            <img class="card-img-top img-responsive" src="http://shashgrewal.com/wp-content/uploads/2015/05/default-placeholder.png" alt="Product Image">
            <% else %>
            <%= image_tag @product.avatar, class: "card-img-top img-responsive"%>
            <% end %>

    </div>
    <% if (@product != nil) %>
        <div class="col-md-5 col-md-offset-0">
            <h3 class="text-right">
            $<%= @product.min_price %></h3>
            <h2><%= @product.name %></h2>
            <p> <%= @product.description %> </p>
            <p class="card-text"><small class="text-muted"> Only <%= @product.inventory_amount %> left!</small></p>
            <p><small>Click or call 800 555 5555 </small></p>
            <%= button_to "Donate", new_charge_path, :method => "get", class: "btn btn-info" %>
            <hr>
            <h5> With the help of donors like you...</h5>
            <br>
            <h5>  We have already raised  </h5>
            <h4> $<%= @product.total_donated_amount %>  </h4>
            <br>
            <h5> Donate, before the fundraiser ends </h5>
            <div class="pull-left" id="countdown"></div>
            <br>
            <hr>
        </div>
    <% else %>
        <h2>No product at this time</h2>
    <% end %>

</div>

app/views/products/new.html.erb
<div class="container">
  <h1 class= "text-center">New Product</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">

      <%= render "form", product: @product %>

      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <h2 class="article-title text-center"><%= @product.name %></h2>
    <br>
    <h4><strong>Description: </strong></h4>
        <% if @product != nil %>
            <h4><%= @product.description %></h4>
        <% else %>
            <h4>n/a</h4>
        <% end %>

    <h4><strong>Minimum Price: </strong>
        <% if @product != nil %>
            <%= @product.min_price %> </h4>
        <% else %>
            <h4>n/a</h4>
        <% end %>

    <h4><strong>Remaining Inventory: </strong> </h4>
        <% if @product != nil %>
           <h4><%= @product.inventory_amount %></h4>
        <% else %>
            <h4>n/a</h4>
        <% end %>

    <h4><strong>Total Donations: </strong></h4>
        <% if @product != nil %>
           <h4>$<%= @product.total_donated_amount %></h4>
        <% else %>
            <h4>n/a</h4>
        <% end %>

    <hr>


    <span><%= link_to "Edit Product", edit_product_path(@product.id) %></span>
    <br>
    <span><%= link_to "All Products", products_path %></span>
    <hr>
    <span class="pull-right"><%= button_to " Delete Product ", {action:"destroy", id: @product.id}, method: :delete, data: { confirm: 'Are you sure?' } %></span>
  </div>
</div>