config/routes.rb
Rails.application.routes.draw do
  # get 'homerails/routes'

  devise_for :users, controllers: { sessions: 'users/sessions' }

  root to: "products#main"
  # User Routes
  get '/users/:id', to: 'users#show', as: 'user'
  patch "/users/:id", to: "users#update"

  get '/users/:id/edit', to: 'users#edit', as: "user_edit"


  # Product Routes
  get "/products", to: "products#index", as: "products"

  get "/products/new", to: "products#new", as: "new_product"

  get "/products/:id", to: "products#show", as: "product"

  post "/products", to: "products#create"

  get "/products/:id/edit", to: "products#edit", as: "edit_product"

  patch "/products/:id", to: "products#update"

  delete "/products/:id", to: "products#destroy"



  # Stripe Charges
  resources :charges, only: [:index, :new, :create]
    

end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :product
  belongs_to :user


  validates :customer_name, presence: true, length: {maximum: 60}
  validates :amount, :product_id, presence: true, :numericality => true


end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController


  def index
    @charges = Charge.all
  end

  def new
    @product = Product.last
    @charge = Charge.new
  end

  def create

    if charge_params

      @product = Product.last

      @amount = params[:amount]

      @amount = @amount.gsub('$', '').gsub(',', '')

      begin
        @amount = Float(@amount).round(2)
      rescue Stripe::CardError => e
        flash[:error] = e.message
        redirect_to new_charge_path
      end

      @amount = (@amount * 100).to_i

      if @amount < @product.min_price
        flash[:error] = 'Charge not completed. Donation amount must be greater than or equal to the minimum price.'
        redirect_to root_path
        return
      end

      Stripe::Charge.create(
        :amount => @amount,
        :currency => 'usd',
        :source => params[:stripeToken],
        :description => 'Donation to Project Fun(d)raiser'
      )

      @charge = Charge.create(charge_params)
      # this assigns the charge to the most recently created product
      # Should provide choice later

      @product.charges << @charge

      @product = @charge.product
      @product.total_donated_amount = @product.total_donated_amount + @charge.amount

      @product.inventory_amount = @product.inventory_amount - 1

      flash[:notice] = "Thank you for your donation!"
      redirect_to root_path
    else
      flash[:error] = "Payment failed"
    end
  end


  private

  def charge_params
    params.require(:charge).permit(:customer_name, :amount, :customer_email, :description, :currency)
  end


end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/index.html.erb
<div class="list-group">

<% @charges.each do |c| %>
  <ul>
    <li class='list-group-item-heading'><%= c.customer_name %></li>
    <li class='list-group-item-text'><%= c.customer_email %></li>
    <li class='list-group-item-text'><%= c.amount %></li>

  </ul>
<% end %>

</div>    

app/views/charges/new.html.erb
<br>
<br>
<div class="container">


  <%= form_tag charges_path do %>
    <article>

      <div id="error_explanation">
        <% if flash[:error].present? %>
          <p><%= flash[:error] %></p>
        <% end %>
      </div>

  <!--     <label class="amount">
        <span>Amount: $5.00</span> -->
      </label>
    </article>
  <% end %>

  <%= form_for @charge do |f| %>
  <div class="form-group">
   <div class="form-group">
     <%= f.label :name %>
     <%= f.text_field :customer_name, placeholder: "Full Name", class: "form-control", id:"cust-name", autofocus: true, :required => true %>
   </div>
   <div class="form-group">
     <%= f.label :email %>
     <%= f.text_field :customer_email, placeholder: "Email", class: "form-control",  id:"cust-email", autofocus: true, :required => true %>
   </div>


   <div class="form-group">
      <%= label_tag(:amount, 'Donation Amount:') %>
      <%= text_field_tag(:amount) %>
      <%= f.hidden_field :amount, id: "cust-amt" %>

      <%= hidden_field_tag(:stripeToken) %>

    </div>

    <button class="btn btn-primary", id='donateButton'>Donate</button>
  <br>
  <% end %>
  <br>
  <!-- prevents donations from being less than min price set in product -->
  <div class="form-group">
      <p>Minimum: $<%= @product.min_price %></p>
      <%= hidden_field_tag :min_price, @product.min_price %>
    </div>



</div>


<script src="https://checkout.stripe.com/checkout.js"></script>
<script>
var handler = StripeCheckout.configure({
  key: '<%= Rails.configuration.stripe[:publishable_key] %>',
  locale: 'auto',
  name: 'Project Fun(d)raiser',
  description: 'One-time donation',
  token: function(token) {
    $('input#stripeToken').val(token.id);
    $('form').submit();
  }
});


$('#donateButton').on('click', function(e) {
  e.preventDefault();

  $('#error_explanation').html('');

  var amount = $('input#amount').val();
  amount = amount.replace(/\$/g, '').replace(/\,/g, '')
  amount = parseFloat(amount);

  var email = $('input#cust-email').val()
  var name = $('input#cust-name').val()
  var minPrice = $('input#min_price').val()


  if (isNaN(amount) || (amount == "")) {
    $('#error_explanation').html('<p class="alert alert-danger">Please enter a valid amount in USD ($).</p>');
    }
  else if (amount < minPrice) {
    $('#error_explanation').html('<p class="alert alert-danger">Donation amount must be equal to or higher than the minimum price.</p>');
  }
  else if (name == "") {
    $('#error_explanation').html('<p class="alert alert-danger">Please enter your full name.</p>');
  }
  else if ( (email == "")) {
    $('#error_explanation').html('<p class="alert alert-danger">Please enter a valid email address.</p>');
  }
  else {
    amount = amount * 100; // Needs to be an integer!
    $('input#cust-amt').val(amount / 100);
    handler.open({
      amount: Math.round(amount)
    })
  }

});
</script>